export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  NATIONAL_ADMIN = 'NATIONAL_ADMIN',
  NATIONAL_ANALYST = 'NATIONAL_ANALYST',
  REGIONAL_ADMIN = 'REGIONAL_ADMIN',
  HOSPITAL_ADMIN = 'HOSPITAL_ADMIN',
  LAB_STAFF = 'LAB_STAFF',
  DISPATCHER = 'DISPATCHER',
  DONOR_COORDINATOR = 'DONOR_COORDINATOR',
  DONOR = 'DONOR',
}

export const ADMIN_ROLES = [
  Role.SUPER_ADMIN,
  Role.NATIONAL_ADMIN,
] as const;

export const STAFF_ROLES = [
  Role.SUPER_ADMIN,
  Role.NATIONAL_ADMIN,
  Role.NATIONAL_ANALYST,
  Role.REGIONAL_ADMIN,
  Role.HOSPITAL_ADMIN,
  Role.LAB_STAFF,
  Role.DISPATCHER,
  Role.DONOR_COORDINATOR,
] as const;

export const HOSPITAL_STAFF_ROLES = [
  Role.HOSPITAL_ADMIN,
  Role.LAB_STAFF,
  Role.DISPATCHER,
  Role.DONOR_COORDINATOR,
] as const;
