# ==================================================
# DonorLink Redis Configuration
# ==================================================

bind 0.0.0.0

protected-mode yes

requirepass donorlink_redis_pass

appendonly yes

maxmemory 256mb

maxmemory-policy allkeys-lru